### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by andreaturli** [cloudsoft/brooklyn-container-service#4]
- to test each PR
- to publish only tag (see https://github.com/openzipkin/zipkin/blob/master/travis/publish.sh as an example)

**Comment by m4rkmckenna** [comment]
@andreaturli Id argue this is not needed as container service will be built by Apache Infra (assuming code contribution is successful)

**Comment by grkvlt** [comment]
@andreaturli this repo is only being used to hold the code before it is (we hope) merged into `apache/brooklyn-server` but I do think we will need to look at how we run the container location live tests on Apache infrastructure once that has happened.

**Comment by grkvlt** [comment]
Closing as ASF projects will not be using Travis for builds

**Comment by andreaturli** [comment]
yeah you are right, it will be an ASF project no need for travis
